rfdetr/deploy/export.py
Fixed the export to be recognized by the paackage.
Tested locally
N/A
-   [ ] Docs updated? What were the changes: N/A
=> Fixed The Export Module

rfdetr/util/misc.py
Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
List any dependencies that are required for this change.
YOUR_ANSWER
=> imports fix

README.md
clarifying the checkpoints avail
Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
List any dependencies that are required for this change.
yes! simple text change
-   [ ] Docs updated? What were the changes: 
N/A
=> Update README.md with checkpoint size callouts

rfdetr/engine.py, rfdetr/main.py, rfdetr/models/lwdetr.py, setup.py
Fixes grad accum to be the same as base model and fixes reinitialization.
locally
no
=> Fix reinitialization / Grad Accum

rfdetr/deploy/export.py, rfdetr/detr.py, rfdetr/main.py
Adds export of model
tested locally
no
=> Allow export

rfdetr/engine.py
Makes sure to use amp args if we import the deprecated or non-deprecated API
tested on both environments
no
=> Fix amp args

rfdetr/engine.py
Autocast kwargs were incorrect in eval but correct in train loop. Pulled out the kwargs constructor so it's consistent and correct.
Tested training and eval locally.
=> refactor autocast kwargs

README.md, pyproject.toml, rfdetr/detr.py, rfdetr/util/metrics.py
- Added `MetricsTensorBoardSink` class that use existing callbacks mechanizm to log metrics to TensorBoard.
- Updated `MetricsPlotSink` to include mAP@0.50 chart.
- Updated README.md to describe how to configure and use TensorBoard
=> TensorBoard support + mAP@0.50 chart saving

README.md, rfdetr/config.py, rfdetr/detr.py, rfdetr/util/metrics.py
Small API updates required after https://github.com/roboflow/rf-detr/pull/70 merge.
=> W&B integration cleanup

README.md, pyproject.toml
- Bump package version
- Update readme
=> Final updates before 1.1.0 release

README.md, pyproject.toml, rfdetr/main.py, rfdetr/util/misc.py
This pull request includes several changes to improve the ONNX export functionality, update dependencies, and clean up the main script. The most important changes include adding a new optional dependency group for ONNX export, updating the README with installation instructions, and cleaning up imports in the main script.
Solves problems mentioned in https://github.com/roboflow/rf-detr/issues/127.
=> Make ONNX-related dependencies optional

rfdetr/engine.py
Fix for rasining error on loss inf
Tested locally
No
-   [ ] Docs updated? What were the changes: No
=> raise error on inf

pyproject.toml
Makes sure to include model configs in package
Installing from commit 
no
=> Add jsons to package

rfdetr/util/misc.py
Dont strip args from best checkpoint bc we read important stuff from there
locally
no
=> Dont strip args

rfdetr/detr.py
Add class_names to model attribute
locally
no
=> save class names

rfdetr/deploy/export.py
Fix wandb dependency to only be imported when requested
Tested locally
No
-   [ ] Docs updated? What were the changes: No
=> Fix wandb import on export

README.md
Update readme with references to inference
n/a
n/a
=> Add inference to README

README.md
=> Fix inference link in readme

README.md
This PR updates the README to include information about new model sizes.
Docs update.
Locally by previewing README.
N/A
N/A
=> Update README with new model sizes

rfdetr/main.py
Allows upload of models that were trained and are in memory (as opposed ot disk)
Tested locally
no
=> Save uploaded num classes

docs/learn/train.md
This PR adds clear documentation for the different types of result checkpoints generated during RF-DETR training, including their purpose, contents, and recommended usage.
=> document RF-DETR result checkpoints
