roboflow/rf-detr

- README.md
* Added new badges for version, license, and Python version to the top of the file.
* Removed outdated information about the `rfdetr` package distribution via PyPI.
-   [X ] Docs updated? What were the changes:
> docs: 📝 pypi,license badges are added and installation section corrected

- rfdetr/detr.py
- rfdetr/main.py
If you stop weights download during the download step, RF-DETR returns:
```python
Loading pretrain weights
Traceback (most recent call last):
File "/Users/james/rf-detr-launch/rfdetr/main.py", line 57, in __init__
checkpoint = torch.load(args.pretrain_weights, map_location='cpu', weights_only=False)
File "/Users/james/rf-detr-launch/venv/lib/python3.13/site-packages/torch/serialization.py", line 1432, in load
with _open_zipfile_reader(opened_file) as opened_zipfile:
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
File "/Users/james/rf-detr-launch/venv/lib/python3.13/site-packages/torch/serialization.py", line 763, in __init__
super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed …
```
> Fix weights download if weights are not properly downloaded

- rfdetr/engine.py
Original Author: https://github.com/fazrigading
Original PR: https://github.com/roboflow/rf-detr/pull/15
Original Description:
Description
Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).
torch.cuda.amp is deprecated as of Pytorch 2.4.
This PR updates use to torch.amp when importing GradScaler and autocast line 24 in rfdetr/engine.py and added 'cuda' args in each usage (line 61, 99, 176).
The purpose is to get rid of this warning:
`torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
List any dependencies that are required for this change.
None required.
Type of change
Bug fix (non-breaking change which fixes an issue) …
> Fix deprecated torch.cuda.amp usage

- README.md
This PR updates the README.md to document that predictions now display class names instead of class IDs in bounding box labels. This enhancement improves the user experience by making detection results more human-readable and interpretable.
The documentation now clearly explains that when users run predictions with the model, object classes will be shown by their descriptive names (e.g., "person", "car") rather than numeric IDs, making it easier to understand detection results at a glance.
This change complements the implementation that converts class IDs to class names in the detection output, creating a more intuitive experience for users of the library.
> Update README to document class name labels in prediction output

- pyproject.toml
- rfdetr/detr.py
- rfdetr/engine.py
- rfdetr/main.py
- rfdetr/util/metrics.py
Added a new class `MetricsPlotSink` that uses the existing callback system to store and save metric values. After training is complete, the loss values obtained at the end of each epoch for the train set and validation set are plotted, as well as the mAP and mAR values for the base and EMA models.
To unlock this feature, a new callback type `on_train_end` has been added.
> save metrics plot once the training is completed

- rfdetr/util/utils.py
Tau wasn't getting used when computing EMA. Fixed.
tested locally on a simple training script, verified EMA decay now changes with tau and seeing much better EMA results, esp early in training
> ensure tau gets used when computing decay

- rfdetr/main.py
We originally used a different learning rate scheduler framework but then switched to LambdaLR and forgot to update our resume training logic. This fixes that.
I am also removing a param group update during the resume. Probably there to make it easier to change learning rates in different parts of the model during resume, but it reeks of code smell to me so I'm taking it out as iirc we don't plan to support that anyway
YOUR_ANSWER
> remove outdated lr scheduler state control for resume

- README.md
- pyproject.toml
- rfdetr/detr.py
- rfdetr/util/metrics.py
- rfdetr/util/misc.py
This pull request introduces a new logging feature to the `rfdetr` package, specifically adding support for Weights and Biases (W&B) logging. The most important changes include importing the necessary W&B module, adding a new class to handle W&B logging, and integrating this new logger into the training process. No depdency updates are needed, since `wandb` is already a dependency.
* [`rfdetr/detr.py`](diffhunk://#diff-9f8117154976f0e714a38740eb63c7b864f2497955660e60fd2c83d8a848c814L15-R15): Imported `MetricsWandBSink` and added the `update` and `save` to the model callbacks.
A sample run that is logged to W&B can be seen below. The setup is similar to Tensorboard, whereas all …
> Add W&B Metric Logging

- README.md
* Added a detailed example of using `InferencePipeline` with custom logic for processing RTSP streams, including a callback for predictions and a method for displaying annotated frames.
* Added an example of using OpenCV for capturing video from an RTSP stream, performing object detection with `RFDETRBase`, and displaying annotated frames.
> docs: 📝 RTSP Stream via Inference and OpenCV Stream examples added to README

- rfdetr/config.py
- rfdetr/main.py
- rfdetr/models/backbone/__init__.py
- rfdetr/models/backbone/backbone.py
- rfdetr/models/backbone/dinov2.py
- rfdetr/models/backbone/dinov2_with_windowed_attn.py
- rfdetr/models/lwdetr.py
Our DINOv2 backbone already supports gradient checkpointing. This PR just pipes the config option to the backbone. 
When training RFDETRLarge, this saves me some 25% memory.
I tested it locally by loading the model via
```
from rfdetr import RFDETRBase, RFDETRLarge
import roboflow
dataset = roboflow.download_dataset("https://universe.roboflow.com/rf100-vl/circuit-voltages-ysajo-tbpd/dataset/1", model_format="coco")
model = RFDETRLarge(resolution=560, gradient_checkpointing=False)
model.train(dataset_dir=dataset.location, epochs=100, batch_size=4, grad_accum_steps=4, …
```
> Support gradient checkpointing to reduce memory load

- rfdetr/config.py
- rfdetr/detr.py
Very minimal change for stability, but this will make sure the class names are in the args which are in the checkpoint, so we will have access to them later for models people are training. Tested locally.
tested training locally, everything saves.
no
> Add class names to args in checkpoint

- rfdetr/config.py
The num_select parameter was not being set correctly, leading to only 100 predictions being returned despite 300 (determined by num_queries) being made. This may be causing a strict decrease in mAP, although that depends on the mAP implementation, don't remember how ours works. Regardless of the impact on mAP this is a required change.
tested locally to confirm we return 300 predictions instead of the prior 100
> add num_select to the config

- rfdetr/main.py
- rfdetr/util/misc.py
Our final checkpoint, checkpoint_best_total.pth, contained optimizer weights and other metadata that caused it to bloat. This PR strips it out. It also ensures that file operations at the end of training only happen in the main process, avoiding potential race condition in multi GPU case.
I tested it locally with a basic train, and confirmed that the checkpoint was about 3x smaller. I also tested that inference works from the saved checkpoint.
> strip final checkpoint for lighter download

- rfdetr/models/backbone/__init__.py
- rfdetr/models/backbone/backbone.py
- rfdetr/models/backbone/dinov2.py
- rfdetr/models/backbone/dinov2_configs/dinov2_base.json
- rfdetr/models/backbone/dinov2_configs/dinov2_large.json
- rfdetr/models/backbone/dinov2_configs/dinov2_small.json
- rfdetr/models/backbone/dinov2_configs/dinov2_with_registers_base.json
- rfdetr/models/backbone/dinov2_configs/dinov2_with_registers_large.json
- rfdetr/models/backbone/dinov2_configs/dinov2_with_registers_small.json
- rfdetr/models/lwdetr.py
Sometimes our network call to huggingface fails, causing our training code to crash. We don't actually need to reach out to huggingface for the DINOv2 weights in the happy path, as we subsequently overwrite them with our pretrained model weights. This PR removes the network call used to download the weights in the case where we're finetuning a pretrained model. It also removes the network call to retrieve the config files, replacing them with local copies.
I verified that I could train the model locally without the call to huggingface. I also verified that the call …
> remove network call to huggingface

- rfdetr/models/lwdetr.py
The standard sigmoidal focal loss has a statistical instability issue due to taking the log of a sigmoid, especially with mixed precision training. Normally we'd protect the log via some epsilon. In this case we can refactor to use a logsigmoid directly.
Here's the basic algebra:
Notice that we've factored out the log(1-sigmoid), which just leaves a single log(sigmoid) term. Because we use a fused logsigmoid, this seems to prevent an inf loss that we experienced for a client earlier.
Trained on the reference dataset that produced the inf loss before and did not produce …
> Stable cross entropy

- rfdetr/detr.py
There was a last minute change in predict batch inference which moved the calculation of the original image size after the resize and this leads to incorrect results
This code should be before the image resize
```
h, w = img_tensor.shape[1:]
orig_sizes.append((h, w))
```
Manually with an image to see I get correct results 
> [BUG] Predict Correct calculation for width, height 

- README.md
- rfdetr/detr.py
- rfdetr/main.py
This PR adds a class_names property to the RFDETR class that dynamically provides access to class names in dictionary format. The property retrieves class names from the loaded model if available, otherwise it falls back to COCO_CLASSES. The class IDs in the dictionary start from 1, providing a consistent interface for class identification. I think this small changes will be mostly suitable for the custom model to get access the class_names with ids.
I have changed the main.py to extract the class_names from model args. And added a property in the detr.py file
Tested with pre-trained models and custom models.
- README.md file is updated
> class names property for easy access

- rfdetr/util/metrics.py
Updates to the `rfdetr/util/metrics.py` file to correct the indexing for `ar50_90` and `ema_ar50_90` metrics. The changes ensure that the correct index is used when extracting these metrics from the evaluation results.
> logging and plotting Average Recall maxDets=100

- rfdetr/datasets/coco.py
- rfdetr/models/lwdetr.py
- rfdetr/models/ops/functions/ms_deform_attn_func.py
- rfdetr/models/transformer.py
Our model currently crashes if the number of patches from the backbone is less than the number of queries. This PR fixes that.
This PR also fixes an issue where training a model at low res causes a failure in the data loader due to the multi scale augmentation trying to get an image resized to negative dimensions.
Finally, I forgot to update a copyright notice 
It's worth noting that I don't think training at super low res like this will yield GOOD results. and there may be a better way to implement this. but at least it won't crash now.
tested training locally with and …
> support low res training

- README.md
Readme instructions are incorrect. Following it results in:
```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 8
5 from rfdetr import RFDETRBase
7 model = RFDETRBase()
----> 8 CLASS_NAMES = model.class_names
10 url = "https://media.roboflow.com/notebooks/examples/dog-2.jpeg"
12 image = Image.open(io.BytesIO(requests.get(url).content))
AttributeError: 'RFDETRBase' object has no attribute 'class_names'
```
YOUR_ANSWER
For example, documentation …
> fix: Readme instructions pointed to obsolete WoW.

- rfdetr/config.py
- rfdetr/main.py
The reported test metrics are not using the best weights, instead using the last weights. This is bad. This is fixed in this PR.
Also fixes a bug where run_test is not defined by default. Now it is both defined and we generate test stats.
Tested locally.
> load best checkpoint for test metrics

- README.md
- docs/index.md
- docs/learn/benchmarks.md
- docs/learn/deploy.md
This PR fixes the `deploy_to_roboflow` docs example, and updates small errors in the README.
This PR also fixes broken links on the docs home page.
Docs change.
Locally by viewing docs and README.
N/A
N/A
> Fix deploy_to_roboflow docs, update README, fix broken link

- README.md
- docs/index.md
- docs/learn/benchmarks.md
- docs/learn/deploy.md
- pyproject.toml
- rfdetr/main.py
* Corrected the `pretrain_weights` path and updated the `deploy_to_roboflow` function in `docs/learn/deploy.md` to fix parameter names and add a `version` argument.
* In `rfdetr/main.py`, added support for setting `class_names` and `num_classes` in the training arguments if provided.
> RF-DETR 1.2.1 release 

- .github/workflows/publish-docs.yml
This PR adds a GitHub Actions workflow to build and deploy RF-DETR documentation to https://rfdetr.roboflow.com/ on pushes to `develop`.
> add GH action to build and deploy docs automatically on every push to `develop`

- docs/tutorials/index.md
- mkdocs.yaml
This PR adds a new /tutorials page that lists various video and blog guides written by the Roboflow team.
You can test this change by running `mkdocs serve` and following the link in the navigation bar to the "Tutorials" page.
N/A
See above.
> Add tutorial grid and page to RF-DETR docs
